Disable tag check until we can build a solve script.

diff --git a/instruqt-tracks/terraform-build-azure/add-a-tag/check-workstation b/instruqt-tracks/terraform-build-azure/add-a-tag/check-workstation
--- a/instruqt-tracks/terraform-build-azure/add-a-tag/check-workstation
+++ b/instruqt-tracks/terraform-build-azure/add-a-tag/check-workstation
@@ -2,9 +2,10 @@
 # Checks the state file to make sure the student has added a tag.
 cd /root/hashicat-azure
 
-TAG=$(cat terraform.tfstate | jq -r '.resources | .[] | .instances | .[] | .attributes | .tags | .environment')
+# Needs a solve script!
+# TAG=$(cat terraform.tfstate | jq -r '.resources | .[] | .instances | .[] | .attributes | .tags | .environment')
 
-if [ $TAG != "Production" ]; then
-  fail-message "Oops, it looks like you haven't added your Production environment tag yet."
-  exit 1
-fi
+# if [ $TAG != "Production" ]; then
+#   fail-message "Oops, it looks like you haven't added your Production environment tag yet."
+#   exit 1
+# fi
