many script updates

diff --git a/instruqt-tracks/terraform-intro-aws/use-a-provisioner/check-workstation b/instruqt-tracks/terraform-intro-aws/use-a-provisioner/check-workstation
--- a/instruqt-tracks/terraform-intro-aws/use-a-provisioner/check-workstation
+++ b/instruqt-tracks/terraform-intro-aws/use-a-provisioner/check-workstation
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -l
 set -e
 
 # Create /tmp/skip-check to disable this check
@@ -7,4 +7,8 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep cowsay main.tf || fail-message "We couldn't find the cowsay install commands in your provisioner inline list."
+cd /root/hashicat-aws
+
+grep -q "cowsay" main.tf || fail-message "We couldn't find the cowsay install commands in your provisioner inline list."
+
+exit 0
diff --git a/instruqt-tracks/terraform-intro-azure/use-a-provisioner/check-workstation b/instruqt-tracks/terraform-intro-azure/use-a-provisioner/check-workstation
--- a/instruqt-tracks/terraform-intro-azure/use-a-provisioner/check-workstation
+++ b/instruqt-tracks/terraform-intro-azure/use-a-provisioner/check-workstation
@@ -7,6 +7,8 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep cowsay main.tf || fail-message "We couldn't find the cowsay install commands in your provisioner inline list."
+cd /root/hashicat-azure
+
+grep -q "cowsay" main.tf || fail-message "We couldn't find the cowsay install commands in your provisioner inline list."
 
 exit 0
diff --git a/instruqt-tracks/terraform-intro-gcp/gcp-credentials/check-workstation b/instruqt-tracks/terraform-intro-gcp/gcp-credentials/check-workstation
--- a/instruqt-tracks/terraform-intro-gcp/gcp-credentials/check-workstation
+++ b/instruqt-tracks/terraform-intro-gcp/gcp-credentials/check-workstation
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -l
 set -e
 
 # Create /tmp/skip-check to disable this check
@@ -7,6 +7,6 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-# With VM-based workstations history isn't written until the user ends the shell session
-# # Hence this check won't work with default settings.
-# grep -q "GOOGLE_CREDENTIALS" /root/.bash_history || fail-message "You haven't checked your credentials yet. We believe in you!"
+grep -q "echo \$GOOGLE_CREDENTIALS" /root/.bash_history || fail-message "You haven't checked your credentials yet."
+
+exit 0
