use assareh/hashicat-gcp for now, don't have working regex to verify GOOGLE_CREDENTIALS yet, updated setup script for gcp output, additional track updates

diff --git a/instruqt-tracks/terraform-build-gcp/setup-our-environment/check-workstation b/instruqt-tracks/terraform-build-gcp/setup-our-environment/check-workstation
--- a/instruqt-tracks/terraform-build-gcp/setup-our-environment/check-workstation
+++ b/instruqt-tracks/terraform-build-gcp/setup-our-environment/check-workstation
@@ -10,6 +10,6 @@ if [ -f /tmp/skip-check ]; then
 fi
 
 # Make sure we have valid GCP credentials in our shell environment
-echo $GOOGLE_CREDENTIALS | grep -P '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' || fail-message "Something went wrong, we were unable to find a valid GOOGLE_CREDENTIALS environment variable in your shell. You may need to restart the track."
+# echo $GOOGLE_CREDENTIALS | grep -P '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' || fail-message "Something went wrong, we were unable to find a valid GOOGLE_CREDENTIALS environment variable in your shell. You may need to restart the track."
 
 [[ -f /bin/set-workdir ]] || fail-message "Uh oh, you're missing the set-workdir script. Please restart your track."
