exit 1 if instruqt test fails 3 times.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,12 +58,15 @@ jobs:
             echo "Running instruqt track test..."
             # Retry instruqt track test up to 3 times
             n=0
-            until [ $n -ge 3 ]
-            do
+            until [ $n -ge 3 ]; do
               instruqt track test --skip-fail-check && break
               n=$[$n+1]
               sleep 5
             done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
   instruqt-test-oss-azure:
     docker:
       - image: ubuntu:latest
@@ -94,12 +97,15 @@ jobs:
             echo "Running instruqt track test..."
             # Retry instruqt track test up to 3 times
             n=0
-            until [ $n -ge 3 ]
-            do
+            until [ $n -ge 3 ]; do
               instruqt track test --skip-fail-check && break
               n=$[$n+1]
               sleep 5
             done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
   instruqt-test-cloud-aws:
     docker:
       - image: ubuntu:latest
@@ -130,12 +136,15 @@ jobs:
             echo "Running instruqt track test..."
             # Retry instruqt track test up to 3 times
             n=0
-            until [ $n -ge 3 ]
-            do
+            until [ $n -ge 3 ]; do
               instruqt track test --skip-fail-check && break
               n=$[$n+1]
               sleep 5
             done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
   instruqt-test-cloud-azure:
     docker:
       - image: ubuntu:latest
@@ -166,12 +175,15 @@ jobs:
             echo "Running instruqt track test..."
             # Retry instruqt track test up to 3 times
             n=0
-            until [ $n -ge 3 ]
-            do
+            until [ $n -ge 3 ]; do
               instruqt track test --skip-fail-check && break
               n=$[$n+1]
               sleep 5
             done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
   instruqt-test-cloud-gcp:
     docker:
       - image: ubuntu:latest
@@ -202,12 +214,15 @@ jobs:
             echo "Running instruqt track test..."
             # Retry instruqt track test up to 3 times
             n=0
-            until [ $n -ge 3 ]
-            do
+            until [ $n -ge 3 ]; do
               instruqt track test --skip-fail-check && break
               n=$[$n+1]
               sleep 5
             done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
   instruqt-test-sentinel:
     docker:
       - image: ubuntu:latest
@@ -238,12 +253,15 @@ jobs:
             echo "Running instruqt track test..."
             # Retry instruqt track test up to 3 times
             n=0
-            until [ $n -ge 3 ]
-            do
+            until [ $n -ge 3 ]; do
               instruqt track test --skip-fail-check && break
               n=$[$n+1]
               sleep 5
             done
+            if [ $n -ge 3 ]; then
+              echo "Instruqt track test failed three times."
+              exit 1
+            fi
 workflows:
   version: 2
   build-and-deploy:
