Fix regression issue with credentials test.

diff --git a/instruqt-tracks/terraform-build-aws/aws-credentials/check-workstation b/instruqt-tracks/terraform-build-aws/aws-credentials/check-workstation
--- a/instruqt-tracks/terraform-build-aws/aws-credentials/check-workstation
+++ b/instruqt-tracks/terraform-build-aws/aws-credentials/check-workstation
@@ -7,4 +7,6 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep -q "AWS_SECRET_ACCESS_KEY" /root/.bash_history || fail-message "You haven't checked your credentials yet. We believe in you!"
+# With VM-based workstations history isn't written until the user ends the shell session
+# # Hence this check won't work with default settings.
+# grep -q "AWS_SECRET_ACCESS_KEY" /root/.bash_history || fail-message "You haven't checked your credentials yet. We believe in you!"
diff --git a/instruqt-tracks/terraform-build-aws/hello-terraform/check-workstation b/instruqt-tracks/terraform-build-aws/hello-terraform/check-workstation
--- a/instruqt-tracks/terraform-build-aws/hello-terraform/check-workstation
+++ b/instruqt-tracks/terraform-build-aws/hello-terraform/check-workstation
@@ -7,5 +7,7 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep -q "terraform version" /root/.bash_history || fail-message "You haven't run terraform version yet. You can do it!"
-grep -q "terraform help" /root/.bash_history || fail-message "You haven't run terraform help yet. We believe in you!"
+# With VM-based workstations history isn't written until the user ends the shell session
+# Hence this check won't work with default settings.
+# grep -q "terraform version" /root/.bash_history || fail-message "You haven't run terraform version yet. You can do it!"
+# grep -q "terraform help" /root/.bash_history || fail-message "You haven't run terraform help yet. We believe in you!"
