remove bash_history checks, inject env vars to code-server

diff --git a/instruqt-tracks/terraform-intro-aws/aws-credentials/check-workstation b/instruqt-tracks/terraform-intro-aws/aws-credentials/check-workstation
--- a/instruqt-tracks/terraform-intro-aws/aws-credentials/check-workstation
+++ b/instruqt-tracks/terraform-intro-aws/aws-credentials/check-workstation
@@ -7,6 +7,6 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep -q "echo \$AWS_SECRET_ACCESS_KEY" /root/.bash_history || fail-message "You haven't checked your credentials yet."
+# grep -q "echo \$AWS_SECRET_ACCESS_KEY" /root/.bash_history || fail-message "You haven't checked your credentials yet."
 
 exit 0
diff --git a/instruqt-tracks/terraform-intro-azure/azure-credentials/check-workstation b/instruqt-tracks/terraform-intro-azure/azure-credentials/check-workstation
--- a/instruqt-tracks/terraform-intro-azure/azure-credentials/check-workstation
+++ b/instruqt-tracks/terraform-intro-azure/azure-credentials/check-workstation
@@ -7,6 +7,6 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep -q "env | grep ARM_CLIENT" /root/.bash_history || fail-message "You haven't checked your Azure credentials yet."
+# grep -q "env | grep ARM_CLIENT" /root/.bash_history || fail-message "You haven't checked your Azure credentials yet."
 
 exit 0
diff --git a/instruqt-tracks/terraform-intro-azure/tf-plan-again/check-workstation b/instruqt-tracks/terraform-intro-azure/tf-plan-again/check-workstation
--- a/instruqt-tracks/terraform-intro-azure/tf-plan-again/check-workstation
+++ b/instruqt-tracks/terraform-intro-azure/tf-plan-again/check-workstation
@@ -7,6 +7,6 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-grep -q "terraform plan" /root/.bash_history || fail-message "You have not re-run terraform plan yet."
+# grep -q "terraform plan" /root/.bash_history || fail-message "You have not re-run terraform plan yet."
 
 exit 0
