Fixes these scripts to they fail when a student hasn't completed the task.

diff --git a/instruqt-tracks/terraform-cloud-aws/oh-no-an-outage/check-workstation b/instruqt-tracks/terraform-cloud-aws/oh-no-an-outage/check-workstation
--- a/instruqt-tracks/terraform-cloud-aws/oh-no-an-outage/check-workstation
+++ b/instruqt-tracks/terraform-cloud-aws/oh-no-an-outage/check-workstation
@@ -14,19 +14,44 @@ TOKEN=$(grep token /root/.terraformrc | cut -d '"' -f2)
 ORG=$(grep organization /root/hashicat-aws/remote_backend.tf | cut -d '"' -f2)
 
 # Check the token length
-[[ 91 -eq $(echo $TOKEN | wc -m) ]] || fail-message "Oops, something's not right with your token. Check your /root/.terraformrc file to be sure it has your token in it."
+[[ 91 -eq $(echo $TOKEN | wc -m) ]]
+EXIT_CODE=$?
+if [[ $EXIT_CODE -ne 0 ]]; then
+  fail-message "Oops, something's not right with your token. Check your /root/.terraformrc file to be sure it has your token in it."
+  exit 1
+fi
 
 # Does the user have an organization configured
-grep -q YOURORGANIZATION /root/hashicat-aws/remote_backend.tf && fail-message "Oops, it looks like you haven't added your organization name to the remote_backend.tf file yet."
+grep -q YOURORGANIZATION /root/hashicat-aws/remote_backend.tf
+EXIT_CODE=$?
+if [[ $EXIT_CODE -eq 0 ]]; then
+  fail-message "Oops, it looks like you haven't added your organization name to the remote_backend.tf file yet."
+  exit 1
+fi
 
 # Does the user have a workspace configured
-grep -q hashicat-aws /root/hashicat-aws/remote_backend.tf || fail-message "Oops, we couldn't find the hashicat-aws workspace in your remote_backend.tf config file. Try again."
+grep -q hashicat-aws /root/hashicat-aws/remote_backend.tf
+EXIT_CODE=$?
+if [[ $EXIT_CODE -ne 0 ]]; then
+  fail-message "Oops, we couldn't find the hashicat-aws workspace in your remote_backend.tf config file. Try again."
+  exit 1
+fi
 
 # Verify the organization exists in TFC
-curl -I -s -L --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request GET https://app.terraform.io/api/v2/organizations/$ORG | grep "HTTP/2 200" || fail-message "I couldn't find your organization, $ORG in Terraform Cloud. Make sure you created it and that it is configured in your remote_backend.tf file."
+curl -I -s -L --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request GET https://app.terraform.io/api/v2/organizations/$ORG | grep "HTTP/2 200"
+EXIT_CODE=$?
+if [[ $EXIT_CODE -ne 0 ]]; then
+  fail-message "I couldn't find your organization, $ORG in Terraform Cloud. Make sure you created it and that it is configured in your remote_backend.tf file."
+  exit 1
+fi
 
 # Verify the workspace exists in TFC
-curl -I -s -L --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request GET https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-aws | grep "HTTP/2 200" || fail-message "I couldn't find the hashicat-aws workspace in your organization $ORG. Make sure you created it and that it is configured in your remote_backend.tf file."
+curl -I -s -L --header "Authorization: Bearer $TOKEN" --header "Content-Type: application/vnd.api+json" --request GET https://app.terraform.io/api/v2/organizations/$ORG/workspaces/hashicat-aws | grep "HTTP/2 200"
+EXIT_CODE=$?
+if [[ $EXIT_CODE -ne 0 ]]; then
+  fail-message "I couldn't find the hashicat-aws workspace in your organization $ORG. Make sure you created it and that it is configured in your remote_backend.tf file."
+  exit 1
+fi
 
 # Store the ORG in /root/.bashrc
 grep $ORG /root/.bashrc || echo "export ORG=\"$ORG\"" >> /root/.bashrc
