finish updating to 1.1.4

diff --git a/instruqt-tracks/terraform-cloud-bonus-lab/setup-our-environment/check-workstation b/instruqt-tracks/terraform-cloud-bonus-lab/setup-our-environment/check-workstation
--- a/instruqt-tracks/terraform-cloud-bonus-lab/setup-our-environment/check-workstation
+++ b/instruqt-tracks/terraform-cloud-bonus-lab/setup-our-environment/check-workstation
@@ -7,4 +7,6 @@ if [ -f /tmp/skip-check ]; then
     exit 0
 fi
 
-[[ -f /bin/set-workdir ]] || fail-message "Uh oh, you're missing the set-workdir script. Please restart your track."
+[[ -f /usr/bin/fastforward ]] || fail-message "Uh oh, you're missing the fastforward script. Please restart your track."
+
+exit 0
